#!/bin/bash
# MySQL 卸载清理脚本（对应安装脚本 scripts/mysql/mysql_silent_install.sh）
# 详见 references/mysql-deploy-guide.md
set -euo pipefail
log_info(){ echo "[$(date '+%F %T')] INFO $*"; }
log_warn(){ echo "[$(date '+%F %T')] WARN $*" >&2; }

INSTALL_PATH="${INSTALL_PATH:-/opt/mysql}"
DATA_PATH="${DATA_PATH:-$INSTALL_PATH/data}"

# 停止 mysqld systemd 服务（服务由 Agent 按 guide 注册）
if systemctl list-unit-files 2>/dev/null | grep -q "^mysqld\.service"; then
    log_info "停止并卸载系统服务 mysqld"
    systemctl disable --now mysqld 2>/dev/null || true
    rm -f /usr/lib/systemd/system/mysqld.service /etc/systemd/system/mysqld.service \
          /etc/systemd/system/multi-user.target.wants/mysqld.service
    systemctl daemon-reload
    systemctl reset-failed mysqld 2>/dev/null || true
fi

# 停止残留进程
# 注意：grep 无匹配返回非零，pipefail 下需 || true 兜底
PIDS=$(ps -ef | grep mysqld | grep -v grep | awk '{print $2}' || true)
if [ -n "${PIDS}" ]; then
    log_info "杀死残留进程: ${PIDS}"
    kill ${PIDS} 2>/dev/null || true
    sleep 2
    kill -9 ${PIDS} 2>/dev/null || true
fi

# 清理目录
log_info "删除安装目录: ${INSTALL_PATH}"
rm -rf "${INSTALL_PATH}"
log_info "删除数据目录: ${DATA_PATH}"
rm -rf "${DATA_PATH}"

# 移除安装脚本生成的全局 my.cnf
if [ -f /etc/my.cnf ] && grep -q "Generated by mysql_silent_install.sh" /etc/my.cnf 2>/dev/null; then
    log_info "移除 MySQL 脚本生成的 /etc/my.cnf"
    rm -f /etc/my.cnf
fi

# 还原 limits.conf 标记块（由 Agent 按 guide 追加）
LIMITS_FILE="/etc/security/limits.conf"
if grep -q "# mysql-limits-begin" "$LIMITS_FILE" 2>/dev/null; then
    log_info "移除 limits.conf 中 mysql 标记块"
    sed -i "/# mysql-limits-begin/,/# mysql-limits-end/d" "$LIMITS_FILE"
fi

# 删除用户组
userdel -r mysql 2>/dev/null || log_warn "mysql 用户删除失败（可能仍有进程占用或已删除）"
groupdel mysql 2>/dev/null || log_warn "mysql 组删除失败（可能非空或已删除）"
log_info "MySQL 卸载清理完成"
