#!/bin/bash
# 生成 DTS 迁移 runtime XML（纯模板渲染器）
#
# 读取模板，替换占位符，输出 runtime XML。非密码字段经 --conf（600 临时文件，source 后即删）传入；
# 密码字段（SRC_PWD、DST_PWD）禁止落盘，由调用方 export（见 data-migration.md「密码处理」）。
#
# 参数：
#   --conf=FILE     600 临时 conf，KEY='VALUE' 格式，仅含非密码字段：
#                    SRC_HOST SRC_PORT SRC_USER SRC_SCHEMA
#                    DST_HOST DST_PORT DST_USER DST_SCHEMA
#                    TABLE_LIST TASK_NAME THREAD_COUNT TO_UPPER (后4项可选)
#   --output=PATH   输出 runtime XML 路径
#   --template=PATH 可选，默认 <脚本目录>/../../assets/dm/dts_runtime_template.xml
# 环境变量：SRC_PWD DST_PWD (由调用方 export)
set -euo pipefail

CONF_FILE=""
OUT=""
TEMPLATE="$(cd "$(dirname "$0")/../../assets/dm" && pwd)/dts_runtime_template.xml"

#==================== 工具函数 ====================
die() { echo "[ERROR] $*" >&2; exit 1; }

usage() { cat <<EOF
用法: $(basename "$0") --conf=FILE --output=PATH [--template=PATH]  （须先 export SRC_PWD DST_PWD）
  --conf=FILE     600 临时 conf，仅含非密码字段，读取后删除
  --output=PATH   输出 runtime XML 路径
  --template=PATH 可选，默认 <脚本目录>/../../assets/dm/dts_runtime_template.xml
EOF
exit 0; }

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --conf=*)     CONF_FILE="${1#*=}" ;;
            --output=*)   OUT="${1#*=}" ;;
            --template=*) TEMPLATE="${1#*=}" ;;
            -h|--help)    usage ;;
            *)             die "未知参数: $1" ;;
        esac; shift
    done
}

#==================== 清理临时 conf ====================
cleanup_conf() {
    [ -n "${CONF_FILE:-}" ] && [ -f "${CONF_FILE:-}" ] && rm -f "${CONF_FILE}" 2>/dev/null || true
}
trap cleanup_conf EXIT

#==================== 加载配置（conf source 后删除；密码从环境变量） ====================
load_conf() {
    [ -n "$CONF_FILE" ] || die "必须指定 --conf=FILE"
    [ -f "$CONF_FILE" ] || die "配置文件不存在: $CONF_FILE"
    local mode
    mode=$(stat -c '%a' "$CONF_FILE" 2>/dev/null || stat -f '%Lp' "$CONF_FILE" 2>/dev/null || echo "")
    [ "$mode" = "600" ] || die "配置文件权限必须为 600，当前: ${mode:-未知}（请 chmod 600 后重试）"
    echo "[INFO] $(date '+%F %T') 加载配置文件: $CONF_FILE"
    # shellcheck disable=SC1090
    source "$CONF_FILE"
    rm -f "$CONF_FILE"
    CONF_FILE=""

    : "${TASK_NAME:=source2dm}"
    : "${THREAD_COUNT:=2}"
    : "${TO_UPPER:=true}"
    : "${SRC_HOST:=127.0.0.1}";  : "${SRC_PORT:=3306}"
    : "${SRC_USER:=root}"
    : "${SRC_SCHEMA:=}"
    : "${DST_HOST:=127.0.0.1}";  : "${DST_PORT:=5236}"
    : "${DST_USER:=SYSDBA}"
    : "${DST_SCHEMA:=$DST_USER}"
    : "${TABLE_LIST:=}"
    : "${SRC_PWD:?SRC_PWD required (export)}"
    : "${DST_PWD:?DST_PWD required (export)}"
}

#==================== 主流程 ====================
parse_args "$@"
[ -n "$OUT" ] || die "必须指定 --output=PATH"
[ -f "$TEMPLATE" ] || die "模板文件不存在: $TEMPLATE"
load_conf

# 输出路径约束：MIGRATION_WORK_DIR 已设置时必须位于 $MIGRATION_WORK_DIR/database/dts_work/ 下
# MIGRATION_WORK_DIR 属于系统级环境变量，由上层 Skill 统一 export，不入参
if [ -n "${MIGRATION_WORK_DIR:-}" ]; then
  case "$MIGRATION_WORK_DIR" in /*) ;; *) die "MIGRATION_WORK_DIR must be absolute" ;; esac
  DTS_WORK_ROOT="$MIGRATION_WORK_DIR/database/dts_work"
  mkdir -p "$DTS_WORK_ROOT" "$MIGRATION_WORK_DIR/database/tmp"
  case "$OUT" in /*) ;; *) OUT="$PWD/$OUT" ;; esac
  OUT_DIR=$(dirname "$OUT")
  mkdir -p "$OUT_DIR"
  DTS_WORK_ROOT=$(cd "$DTS_WORK_ROOT" && pwd -P)
  OUT_DIR=$(cd "$OUT_DIR" && pwd -P)
  case "$OUT_DIR/" in "$DTS_WORK_ROOT/"*) ;; *) die "output xml must be under $DTS_WORK_ROOT" ;; esac
  export TMPDIR="$MIGRATION_WORK_DIR/database/tmp" TMP="$MIGRATION_WORK_DIR/database/tmp" TEMP="$MIGRATION_WORK_DIR/database/tmp"
fi

# 生成 TransformItem 列表（多行字符串，与 python "\n".join(items) 行为一致：末尾不加换行）
# 支持 schema.table 或纯 table（纯表名 schema 取 SRC_SCHEMA）
ITEMS=""
ITEM_COUNT=0
if [ -n "$TABLE_LIST" ]; then
  for token in $TABLE_LIST; do
    case "$token" in
      *.*)
        s="${token%%.*}"
        t="${token#*.}"
        ;;
      *)
        s="$SRC_SCHEMA"
        t="$token"
        ;;
    esac
    if [ -n "$ITEMS" ]; then
      ITEMS="${ITEMS}"$'\n'
    fi
    ITEMS="${ITEMS}    <TransformItem id=\"0\" type=\"table\" sourceSchema=\"${s}\" destSchema=\"${DST_SCHEMA}\" source=\"${t}\" destination=\"${t}\" isDefinitionAutoGenerated=\"true\" customColumnMap=\"false\" partitionAsList=\"false\"/>"
    ITEM_COUNT=$((ITEM_COUNT + 1))
  done
fi

# 确保输出目录存在
OUT_DIR=$(dirname "$OUT")
mkdir -p "$OUT_DIR"

# awk 模板渲染：-v 传变量，index()+substr() 纯字符串替换（避免正则元字符问题），{TRANSFORM_ITEMS} 多行经 -v 传入
awk -v TASK_NAME="$TASK_NAME" \
    -v SRC_HOST="$SRC_HOST" \
    -v SRC_PORT="$SRC_PORT" \
    -v SRC_USER="$SRC_USER" \
    -v SRC_PWD="$SRC_PWD" \
    -v SRC_SCHEMA="$SRC_SCHEMA" \
    -v DST_HOST="$DST_HOST" \
    -v DST_PORT="$DST_PORT" \
    -v DST_USER="$DST_USER" \
    -v DST_PWD="$DST_PWD" \
    -v DST_SCHEMA="$DST_SCHEMA" \
    -v THREAD_COUNT="$THREAD_COUNT" \
    -v TO_UPPER="$TO_UPPER" \
    -v ITEM_COUNT="$ITEM_COUNT" \
    -v ITEMS="$ITEMS" \
'
BEGIN {
  # 单值占位符与值映射
  n = 13
  keys[1]  = "{TASK_NAME}";     vals[1]  = TASK_NAME
  keys[2]  = "{SRC_HOST}";     vals[2]  = SRC_HOST
  keys[3]  = "{SRC_PORT}";     vals[3]  = SRC_PORT
  keys[4]  = "{SRC_USER}";     vals[4]  = SRC_USER
  keys[5]  = "{SRC_PWD}";      vals[5]  = SRC_PWD
  keys[6]  = "{SRC_SCHEMA}";   vals[6]  = SRC_SCHEMA
  keys[7]  = "{DST_HOST}";     vals[7]  = DST_HOST
  keys[8]  = "{DST_PORT}";     vals[8]  = DST_PORT
  keys[9]  = "{DST_USER}";     vals[9]  = DST_USER
  keys[10] = "{DST_PWD}";      vals[10] = DST_PWD
  keys[11] = "{DST_SCHEMA}";   vals[11] = DST_SCHEMA
  keys[12] = "{THREAD_COUNT}"; vals[12] = THREAD_COUNT
  keys[13] = "{TO_UPPER}";    vals[13] = TO_UPPER
  ic_key = "{ITEM_COUNT}";     ic_len = length(ic_key)
  ti_key = "{TRANSFORM_ITEMS}"; ti_len = length(ti_key)
}
{
  line = $0
  # 单值占位符替换（index 纯字符串查找，无正则元字符问题）
  for (i = 1; i <= n; i++) {
    klen = length(keys[i])
    while ((idx = index(line, keys[i])) > 0) {
      line = substr(line, 1, idx - 1) vals[i] substr(line, idx + klen)
    }
  }
  # {ITEM_COUNT}
  while ((idx = index(line, ic_key)) > 0) {
    line = substr(line, 1, idx - 1) ITEM_COUNT substr(line, idx + ic_len)
  }
  # {TRANSFORM_ITEMS} 替换为多行 ITEMS 内容
  while ((idx = index(line, ti_key)) > 0) {
    line = substr(line, 1, idx - 1) ITEMS substr(line, idx + ti_len)
  }
  print line
}
' "$TEMPLATE" > "$OUT"

chmod 600 "$OUT"
echo "GENERATED $OUT ($ITEM_COUNT tables)"
